name: checks
on: [push, pull_request]
jobs:
  test:
    name: test py${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # - name: Install dependencies
      #   run: |
      #     python3 -m pip install ".[tests]"
      - uses: yezz123/setup-uv@v4
      - run: uv pip install --system -r pyproject.toml --extra tests

      - name: Run tests
        run: uv run pytest tests/test_dgidb.py
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: yezz123/setup-uv@v4

      - name: Install dependencies
        run: uv pip install --system ".[dev]"

      - name: Check style
        run: uv run ruff check . && uv run ruff format --check .

  docs:
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.SPHINX_GITHUB_CHANGELOG_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - uses: yezz123/setup-uv@v4

      - name: Install dependencies
        run: uv pip install --system ".[docs]"

      - name: Attempt docs build
        working-directory: ./docs
        env:
          SPHINXBUILD: uv run sphinx-build
        run: make html
